# Generated by Django 5.1.2 on 2025-10-29 05:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0007_payment_order_id_payment_payment_id_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='dailytask',
            name='question',
            field=models.TextField(blank=True, null=True),
        ),
    ]
