# Generated by Django 5.1.2 on 2025-11-04 07:06

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0012_alter_course_image'),
    ]

    operations = [
        migrations.RenameField(
            model_name='livesession',
            old_name='meeting_link',
            new_name='join_url',
        ),
        migrations.RemoveField(
            model_name='livesession',
            name='duration_minutes',
        ),
        migrations.RemoveField(
            model_name='livesession',
            name='title',
        ),
        migrations.AddField(
            model_name='livesession',
            name='duration',
            field=models.IntegerField(default=60),
        ),
        migrations.AddField(
            model_name='livesession',
            name='start_url',
            field=models.URLField(default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='livesession',
            name='topic',
            field=models.CharField(default=1, max_length=255),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='livesession',
            name='course',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='live_sessions', to='myapp.course'),
        ),
        migrations.AlterField(
            model_name='livesession',
            name='instructor',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
