# Generated by Django 5.1.2 on 2025-11-04 07:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0013_rename_meeting_link_livesession_join_url_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='livesession',
            name='join_url',
            field=models.URLField(max_length=1000),
        ),
        migrations.AlterField(
            model_name='livesession',
            name='start_url',
            field=models.URLField(max_length=1000),
        ),
    ]
