# Generated by Django 5.1.2 on 2025-11-04 10:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0014_alter_livesession_join_url_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='livesession',
            name='zoom_meeting_id',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
