# Generated by Django 5.1.2 on 2025-11-09 11:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0020_coursechatmessage'),
    ]

    operations = [
        migrations.AddField(
            model_name='coursechatmessage',
            name='is_read',
            field=models.BooleanField(default=False),
        ),
    ]
