# Generated by Django 5.1.2 on 2025-11-14 10:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0023_remove_message_chatroom_remove_message_sender_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='course_duration_months',
            field=models.PositiveIntegerField(default=6),
        ),
        migrations.AddField(
            model_name='enrollment',
            name='expires_on',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
